version: '1.0'
services:
  azatapi:
    image: "azattekce/azatapi:v3"
    build:
      context: .
      dockerfile: /Azat.ApiGateway/Dockerfile
    container_name: Azatapi
    hostname: Azatapi    
    restart: always
    ports:
      - 7124:80
    environment:
      - ASPNETCORE_ENVIRONMENT=${Env}
    #dns:
    #  - 8.8.8.8
    extra_hosts:
      - "host.docker.internal:host-azatapi"
