version: '1.1'
services:
  azatapi:
    #image: "azattekce/azatapi6_img"
    build:
      context: .
      dockerfile: ./Azat.ApiGateway/Dockerfile
    container_name: Azatapi
    hostname: Azatapi    
    restart: always
    ports:
      - 5006:80
    volumes:
           - /opt/data:/app/azatapi
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=${Env}
    #dns:
    #  - 8.8.8.8
    #extra_hosts:
     # - "host.docker.internal:host-azatapinew"
